#!/bin/bash

set -e

if [ "$1" != "true" ]; then
    [ "$(kreadconfig5 --key LookAndFeelPackage)" == "Sweetified Plasma" ] && [ "$(kreadconfig5 --key ColorScheme)" == "Sweet" ] && [ "$(kreadconfig5 --key widgetStyle)" == "kvantum-dark" ]
    [ -f ~/.config/autostart/org.kde.latte-dock.desktop ]
    [ -x /usr/bin/latte-dock ]
else
    backup=(kwinrc kcminputrc kdeglobals plasmarc ksplashrc kscreenlockerrc)
    for i in "${backup[@]}"; do
        cp "$HOME/.config/$i" "$HOME/.config/$i.bak"
    done

    # Remove Kwin keys, this is not done by lookandfeeltool
    sed -i 's&Meta=org.kde.plasmashell,/PlasmaShell,org.kde.PlasmaShell,activateLauncher&&g' kwinrc
    sed -i 's&\[ModifierOnlyShortcuts\]&&g' kwinrc

    lookandfeeltool --resetLayout -a Dr460nized
    rm ~/.config/autostart/org.kde.latte-dock.desktop
    killall -SIGINT latte-dock
fi
