#!/bin/bash
# $1 Update garuda-hotfixes

set -e
shopt -s extglob

# Systemd replaces - with / for some reason... See %i man page entry for systemd.unit
if [ "$1" == "keyring/hotfixes" ]; then
    packages="archlinux-keyring chaotic-keyring garuda-hotfixes"
elif [ "$1" == "keyring" ]; then
    packages="archlinux-keyring chaotic-keyring"
fi

rm -r /tmp/garuda-system-maintenance/cache || true
mkdir -p /tmp/garuda-system-maintenance/{db,cache}
pacman -b /tmp/garuda-system-maintenance/db --cachedir /tmp/garuda-system-maintenance/cache --noconfirm -Sywdd $packages
pushd /tmp/garuda-system-maintenance/cache
SKIP_AUTOSNAP=1 pacman -U --noconfirm --needed !(*.sig)
popd
rm -r /tmp/garuda-system-maintenance/{db,cache} || true
